dependencies:
  - python

build_dependencies:
  - libslurm-dev
  - python-dev
  - python-setuptools
  - cython

targets:
  ubuntu-16-04:
  debian-8:
  centos-6:
  centos-7:
  sles-11:
  sles-12:

cli: false
notifications: false
